components/canvas/utils/assetGenerators/GetRoleText.ts
Fix #90 
Bug with ID 71:In sub-activities; when the role is above a certain length it is divided over two lines. The second line interrupts with the time input on the cards. An example from project 139 is the role “Operation engineer”. The word “Operation” sits in the first row, while the second row has “engine” in it, on top of the time.
https://equinor-sds-si.atlassian.net/browse/VSM-163
=> Role should be only one line

pages/index.tsx
increased from 19 to 100 since filtering (hiding project without name) is done on the client side.
it looks bad when every other page just have a few cards and others have more... Therefore it would be better to just show a greater amount of cards at once
=> Increase amount of projects shown on every page + don't show pagination if only one page

components/canvas/utils/FormatCanvasText.ts, components/canvas/utils/assetGenerators/CreateChoiceAsset.ts, components/canvas/utils/assetGenerators/CreateGenericCardAsset.ts, components/canvas/utils/assetGenerators/CreateMainActivityAsset.ts, components/canvas/utils/assetGenerators/CreateSubActivityAsset.ts, components/canvas/utils/assetGenerators/GetRoleText.ts, components/canvas/utils/assetGenerators/GetTimeText.ts
Add support for multiple lines in the cards on the canvas.
Solved by adding a mask on the text. This might have some performance impact...
> Feedback ID32: In all post-it boxes, the text is visualized as one long paragraph. I would like to see the card with the same layout as my original input, including returns and spaces between paragraphs.
fixes #103 vsm-169
=> Display newlines in cards

components/ExistingTaskSection.tsx
fixes #105 vsm-170
Using a hover instead of using multiple lines in the list 
If we put it on multiple lines, the list might look bad. Would like to talk with our designer before doing any changes there.
=> Hover tooltip to read the whole description when adding existing QIP

components/DurationComponent.tsx, components/SideBarBody.tsx, components/SideBarContent.tsx, pages/projects/[id]/qips/[taskId].tsx
There was a problem where the time was not saved when adding the unit first. Issue was some async calls to api overwriting each others... Fixed by always sending time and unit together.
fix #111
=> fix(durationcomponent): fix erros when updating time on a card

components/DurationComponent.tsx
We got a bug where a request to update the time is sent every time the DurationComponent is loaded.
Expected: Only send patch-update when user makes a change.
fix #139 improve #111
=> fix(duration): do not send request when no change

interfaces/VsmProject.tsx, pages/projects/[id]/duplicate.tsx, utils/DownloadJSON.ts
PO wants a small change of the title when creating new project based on another one. 
> The title on a duplicate would be better if it was "Title (Duplicate of xx)" instead of "Duplicate of Title (xx)"
Fix #117
Add `duplicateOf` field to new project request when the new project is a duplicate.
Field `duplicateOf` contains a string of the `vsmProjectId` that a new project is duped from
fix #147
=> PO requested changes

pages/processes/favourite.tsx, pages/processes/index.tsx, pages/processes/mine.tsx, services/projectApi.ts, utils/createUrlParams.ts
Search-query needs to be url-encoded for the fetch-request to be parsed correctly. Considering
special characters...
fix #277
=> fix: url-encode the search query

pages/processes/mine.tsx, services/projectApi.ts, utils/createUrlParams.ts, utils/getProjectCardsArray.tsx
API change requires us to send in userIds as numbers instead of the shortNames we used before.
Therefore getting my UserId from another api-call
fix #286
=> fix: only show my projects in the myProjects tab

utils/createUrlParams.ts
Bug #225-resurfaced in PR #278 because we forgot to url-encode the search query.
Fixes #291
=> fix: support searching with special characters like & (url-encode search queries)

commitHash.ts, components/AccessBox.tsx
=> feat(access): add multiple users to a process quickly by supplying comma separated string

components/canvas/Canvas.tsx
As a user, you may now move around the canvas by holding down either the left or right mouse-button.
The context-menu is disabled and wont be in your way.
close #399
=> feat: right click and drag around in canvas

components/Card/ProjectCard.tsx
Fixes a bug where an owner of a process were unable to delegate roles from landing page.
Closes #410
=> fix: Owner cannot delegate roles from landing page

radixconfig-template.yaml, radixconfig.yaml
Removes the certificate for vsm.equinor.com since we no longer use it. We use flyt.equinor.com instead.
Closes #480
=> chore: Remove certificate

tsconfig.json
Use the default TypeScript config from a freshly generated Create Next App project. This change makes the TypeScript compiler use strict mode which will detect more type errors in the editor before you build and run the application.
Closes #503
=> chore: Use default TypeScript config

tsconfig.json
Disable all strict type checking options in the TypeScript compiler.
Closes #509
=> chore: Disable strict mode in TypeScript

pages/_document.tsx, styles/_variables.scss
Use the new Equinor CDN for getting the Equinor Font since the old CDN is getting removed.
Closes #534
=> chore: Use the new Equinor CDN

.github/workflows/pr-lint.yaml
Adds a GitHub Action which lints pull request titles for conventional commits.
Closes #581
=> ci: Add pull request title linter

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
- Add threat modeling to issue templates as a development task to make sure threat modeling is done when solving an issue.
Closes #613
=> docs(issue-templates): Add Threat Modeling task

components/canvas/Canvas.tsx
The process view was showing the previously viewed process if the most recently viewed process was empty. An empty process will now be displayed if the root of the process is not found.
Closes #692
=> fix: Render empty process

components/DeleteNodeDialog.tsx, components/ScrimDelete.tsx, components/TypographyMarkdown.tsx
When deleting a main activity or choice with children, the warning message will now say:
> This will delete **ALL** the cards below. Are you sure you want to proceed?
Closes #805
=> feat: update delete choice/main activity warning text

components/canvas/ChoiceNode.tsx, components/canvas/LinkedProcessNode.tsx, components/canvas/MainActivityNode.tsx, components/canvas/Node.module.scss, components/canvas/NodeDelete.tsx, components/canvas/SubActivityNode.tsx, components/canvas/WaitingNode.tsx, components/canvas/hooks/useFlowState.tsx, components/canvas/utils/createNodes.tsx, types/NodeData.ts, utils/canDeleteNode.ts
Added delete icon to the following nodes
Attached reference of working example.
https://github.com/user-attachments/assets/0a3dedf8-a891-4b05-b1ba-f766ee7b5c6a
=> feat: delete card button

components/AccessBox.tsx, components/RoleSelect.tsx, components/UserItem.tsx, components/UserSearch.tsx, components/canvas/hooks/useAccess.tsx, layouts/canvas.tsx, layouts/default.layout.module.scss, types/AccessRoles.ts, types/UserAccessRole.tsx, utils/getOwner.ts
=> feat: All roles combined into Contributor role
