equinor/flyt

- components/accessBox.tsx
> Change share-text to "You need to be owner or admin to manage sharing"

- components/Card/Card.module.scss
- components/Card/LoadingVSMCard.module.scss
- components/Card/LoadingVSMCard.tsx
- components/WashOutFilter/WashOutFilter.module.scss
- components/WashOutFilter/WashOutFilter.tsx
- components/projectListSection.tsx
- package.json
- pages/index.tsx
- pages/projects/Projects.module.scss
- services/projectApi.ts
- styles/common.module.scss
- utils/createUrlParams.ts
- utils/getMyAccess.tsx
- utils/getUserName.tsx
- yarn.lock
closes #93
Had to update the project page to support the new API changes for filtering projects.
Also tried out some animation with layout-hints before loading.
> init new project-page | Support new api features

- pages/index.tsx
- utils/categorizeProjects.tsx
But show your own projects with no name in both modes.
> Hide projects with no name that I don't have access to

- pages/index.tsx
Fixes that the page-indicator "resets" to 1 when you navigate and load new content.
> improve pagination interaction

- components/VSMCanvas.module.scss
- components/VSMSideBar.tsx
Feedback ID37: I would like to have the feature that if I have a card open (panel on the right to insert the text) that it closed when I click on the white screen again instead of using the cross.
fixes #104 vsm-171
> Hide the sidebar if click on canvas #104

- layouts/canvas.tsx
- pages/projects/[id]/duplicate.tsx
- services/projectApi.ts
- utils/DownloadJSON.ts
click on the duplicate button in the vsm-title-dropdown to create a new vsm with the same cards.
Note; Questions, Ideas and Problems are not copied.
fix #117
> feat: create new vsm based on an existing one

- components/MySnackBar.tsx
Change message visible regardless of having side bar open
fix #130
> fix(snackmessage): display notifications on top over the sidesheet

- components/CircleButton.module.scss
> fix: center plus sign in add button

- pages/labels/bulkAdd.tsx
- pages/labels/index.tsx
- services/labelsApi.ts
This is the beginning of a simple admin interface for labels. Currently only supporting creating
labels in bulk. `/labels/bulkAdd`
> feat(labels): simple admin for labels

- layouts/canvas.tsx
As a user I want to mark a process as a favourite from the canvas so that I don't have to exit the
process and find it again in the landing page to mark it
fix #252
> feat: favourite a process from the canvas

- CHANGELOG.md
- commitHash.ts
- components/SortSelect.tsx
- package.json
- pages/processes/favourite.tsx
- pages/processes/index.tsx
- pages/processes/mine.tsx
- services/projectApi.ts
Fix the ordering of the processes and set default ordering to last modified
fix #378
> fix: ordering of processes

- components/FrontPageBody.tsx
- components/NewProcessButton.tsx
- components/NewProjectButton.module.scss
- components/ProjectListSection.tsx
- pages/processes/favourite.tsx
- pages/processes/index.tsx
- pages/processes/mine.tsx
Update styling to match Figma and disable the button when it sending the request
fix #388
> fix: Missing loading spinner when creating new project

- components/Card/ProjectCard.tsx
- components/Card/ProjectCardHeader.tsx
- components/Card/UserDots.tsx
- components/UserDot.tsx
- components/canvas/entities/toolbox/createToolboxChoice.tsx
- components/canvas/entities/toolbox/createToolboxMainActivity.tsx
- components/canvas/entities/toolbox/createToolboxSubActivity.tsx
- components/canvas/entities/toolbox/createToolboxWaiting.tsx
- components/canvas/utils/addNewVsmObjectToHoveredCard.ts
- interfaces/UserAccess.tsx
- interfaces/VsmProject.tsx
- pages/process/[id]/duplicate.tsx
- utils/DownloadJSON.ts
Adjust where we get our data from to match the api change
fix #383  & fix #382
> fix: display user accesses on front page

- CHANGELOG.md
- package.json
> chore(release): 0.2.22

- package.json
- yarn.lock
- Remove unused dependency
Closes #468
> chore: Patch vulnerabilities

- CHANGELOG.md
- package.json
> chore(release): 0.2.23

- CHANGELOG.md
- package.json
> chore(release): 0.2.24

- CHANGELOG.md
- package.json
> chore(release): 0.2.25

- components/VSMSideBar.tsx
Fix issue with card description in sidepanel that is lagging behind.
Closes #411
> fix: Invalidate reactQuery

- next.config.js
By adjusting HTTP headers the application will be more secure.
Closes #506
> chore: Adjust HTTP headers to improve security

- CHANGELOG.md
- package.json
> chore(release): 0.2.26

- CHANGELOG.md
- package.json
> chore(release): 0.2.27

- CHANGELOG.md
- package.json
> chore(release): 0.2.28

- .github/workflows/release-please.yml
Release Please automates CHANGELOG generation, the creation of GitHub releases, and version bumps.
Closes #431
> chore: Add Release Please

- Dockerfile
- yarn.lock
- Updated `node` and `alpine` versions in Dockerfile
- Generated new `yarn.lock`
Closes #572
> deps: Patch vulnerabilities

- yarn.lock
Generated new `yarn.lock`.
Closes #585
> fix(deps): Patch vulnerabilities

- package.json
- yarn.lock
> fix(deps): Upgrade axios from 0.25.0 to 1.6.1

- radixconfig.yaml
> chore: Remove dev alias

- yarn.lock
- Generate a new yarn.lock.
Closes #701
> fix: Upgrade dependencies

- radixconfig.yaml
> chore: Enable certificate automation

- components/EditTaskSection.tsx
- components/EditTaskTextField.tsx
- components/NewTaskSection.tsx
Added markdown editor to PQIR TextField to support link injection.
> feat: links in pqirs

- components/canvas/MiniMapCustom.tsx
fixes issue reported in qa for minimap #473
> feat: display rhombus shape for choice nodes in minimap

- services/CommonAPIService.ts
closes https://github.com/equinor/mad-team/issues/519
> fix: update mad api base url

- components/canvas/NodeTooltip.tsx
- utils/unitDefinitions.tsx
> revert: "feat: Added seconds as option in duration unit"

- components/DeleteNodeDialog.tsx
Attached the reference of working solution
https://github.com/user-attachments/assets/b723f759-60d0-4c2d-a80c-bd5b273baa02
> feat: updated the linked process delete confirmation message.

- components/AccessBox.tsx
- components/RoleSelect.tsx
- components/UserItem.tsx
- components/UserSearch.tsx
- components/canvas/hooks/useAccess.tsx
- layouts/canvas.tsx
- layouts/default.layout.module.scss
- types/AccessRoles.ts
- types/UserAccessRole.tsx
- utils/getOwner.ts
Attached the screenshot for reference
> feat: All roles combined into Contributor role

- components/AccessBox.tsx
- components/RoleSelect.tsx
- components/UserItem.tsx
- components/UserSearch.tsx
- components/canvas/hooks/useAccess.tsx
- layouts/canvas.tsx
- layouts/default.layout.module.scss
- types/AccessRoles.ts
- types/UserAccessRole.tsx
- utils/getOwner.ts
> Revert "feat: All roles combined into Contributor role"

- components/LiveIndicator.module.scss
- components/LiveIndicator.tsx
- components/canvas/Canvas.tsx
@MozillaFirefox Version 128.6.0esr
@Safari
> feat: Hide Current/To Be toggle

- components/canvas/hooks/useNodeDrag.tsx
- services/graphApi.ts
When main activity is dropped on top of other main activities to the left. The activities should change the order.
https://github.com/user-attachments/assets/693dc142-6157-41ca-b37e-a95248ff3ac5
> fix: Rearrange the mainactivity to left

- components/Card/UserDots.tsx
> fix: 833-user-dots-change-order

- utils/getCategorizedLabels.ts
Sorted labels in each category
> feat: Sorted labels alphabetically in each category

- components/canvas/utils/getEdgeOrder.tsx
- components/canvas/utils/getLayout.ts
> fix: wrong order choice children

- package.json
- yarn.lock
Upgraded next from 14.2.4 to 15.2.2
Upgraded socket.io from 4.7.5 to 4.8.0
> fix: Snyk issues Upgrade packages next and socket.io

- components/ExportCategory/ExportButton.tsx
- pages/process/[id]/categories/index.tsx
- types/ExportFormat.ts
- utils/getFormattedPQIRData.ts
> feat: Changed Stakeholder header to role and changed the export button
